2024-01-13 01:01:26.154 [info] Default formatter is set to null for workspace /home/aexyzk/verlauf/verlauf
2024-01-13 01:01:26.154 [info] Test server listening.
2024-01-13 01:01:26.154 [info] > conda info --json
2024-01-13 01:01:26.155 [info] Found: /bin/python --> /bin/python3.11
2024-01-13 01:01:26.155 [info] Found: /bin/python3 --> /bin/python3.11
2024-01-13 01:01:26.155 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-01-13 01:01:26.156 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:26.156 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-01-13 01:01:26.163 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-01-13 01:01:26.174 [info] Found: /sbin/python --> /sbin/python3.11
2024-01-13 01:01:26.174 [info] Found: /sbin/python3 --> /sbin/python3.11
2024-01-13 01:01:26.174 [info] Found: /sbin/python3.11 --> /sbin/python3.11
2024-01-13 01:01:26.178 [info] Found: /usr/bin/python --> /usr/bin/python3.11
2024-01-13 01:01:26.178 [info] Found: /usr/bin/python3 --> /usr/bin/python3.11
2024-01-13 01:01:26.178 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-01-13 01:01:26.198 [info] Found: /usr/sbin/python --> /usr/sbin/python3.11
2024-01-13 01:01:26.198 [info] Found: /usr/sbin/python3 --> /usr/sbin/python3.11
2024-01-13 01:01:26.198 [info] Found: /usr/sbin/python3.11 --> /usr/sbin/python3.11
2024-01-13 01:01:26.211 [info] > /bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/interpreterInfo.py
2024-01-13 01:01:26.221 [info] > /sbin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/interpreterInfo.py
2024-01-13 01:01:26.250 [info] > /usr/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/interpreterInfo.py
2024-01-13 01:01:26.261 [info] > /usr/sbin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/interpreterInfo.py
2024-01-13 01:01:26.321 [error] [
  'Failed to activate a workspace, Class name = g, completed in 202ms, has a falsy return value, Arg 1: <Uri:/home/aexyzk/verlauf/verlauf/__main__.py>, Return Value: undefined',
  [Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
  Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
   The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
  	at v (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:138:48007)
  	at get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:158:23805)
  	at w.activate (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:795716)
  	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2455
  	at Array.map (<anonymous>)
  	at g.activateWorkspace (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2445)]
]
2024-01-13 01:01:26.321 [error] Failure during activation. [Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at v (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:138:48007)
	at get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:158:23805)
	at w.activate (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:795716)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2455
	at Array.map (<anonymous>)
	at g.activateWorkspace (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2445)]
2024-01-13 01:01:26.321 [error] sendStartupTelemetry() failed. [Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at v (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:138:48007)
	at get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:158:23805)
	at w.activate (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:795716)
	at /home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2455
	at Array.map (<anonymous>)
	at g.activateWorkspace (/home/aexyzk/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/out/client/extension.js:2:2445)]
2024-01-13 01:01:26.323 [info] Python interpreter path: /bin/python
2024-01-13 01:01:26.324 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-13 01:01:27.244 [info] Starting Jedi language server for verlauf.
2024-01-13 01:01:28.809 [info] Send text to terminal: /bin/python /home/aexyzk/verlauf/verlauf/__main__.py
2024-01-13 01:02:39.536 [info] Send text to terminal: /bin/python /home/aexyzk/verlauf/verlauf/__main__.py
2024-01-13 01:02:41.432 [info] Send text to terminal: /bin/python /home/aexyzk/verlauf/verlauf/__main__.py
